version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            sudo pip install -r requirements.txt
            mkdir results
      - run:
          command: |
            tox -e flake8
      - run:
          command: |
            tox -e py27 -- --junitxml=results/py27.xml
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
          destination: results
