import os
import sys
import subprocess

class VersionError(Exception):
    pass

try:
    import _version
    VERSION = _version.VERSION
except ImportError:
    VERSION = None

def version():
    return VERSION

def version_str():
    ver = version()

    if ver is None:
        return "<unknown>"
    return ver

def generate(base_path):
    popen = subprocess.Popen(["svnversion", base_path],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)

    stdout, stderr = popen.communicate()
    if popen.returncode:
        raise VersionError(stderr.strip())

    ver = stdout.strip()

    version_dir, _ = os.path.split(__file__)
    module_file = open(os.path.join(version_dir, "_version.py"), "rw")
    print >> module_file, "# This is an autogenerated file. Do not touch."
    print >> module_file, "VERSION =", repr(ver)
    module_file.close()

    global VERSION
    VERSION = ver
