service_room = "FIXME.lobby"
accesslog_room = service_room + ".accesslog"
combined_room = service_room + ".combined"
path = ""
xmpp_jid = ""
xmpp_password = "FIXME"
xmpp_ignore_cert = True
xmpp_extra_ca_certs = None
xmpp_rate_limit = 10
