#!/bin/sh 
myerr() {
 echo "$*" >&2
 exit 1
}


PYTHON="python"
UNAME=$(uname)
CFG="/etc/abusehelper/config.ini"
INSTALLROOT=""
LOGDIR="${INSTALLROOT}/var/log/abusehelper"
LOG="${LOGDIR}/abusehelper.log"
USER="abusehel"

case "${UNAME}" in
    "Darwin")
	SU="su -"
	;;
    "OpenBSD")
        [ ! -f "/usr/local/bin/python2.5" ] && myerror "python2.5 not found"
        SU="su -" 
        PYTHON="python2.5" 
        STOPCMD="${PYTHON} -m -c $CFG"
	USER="_abusehe"
	;;
    *)
	SU="su -s /bin/sh"
	;;
esac

AHCMD="${PYTHON} -m abusehelper.core.startup" 
STARTCMD="${AHCMD} ${CFG}"

# Default, ${STARTCMD} = ${STOPCMD}. OpenBSD behaves slightly differently.
[ -z "${STOPCMD}" ] && STOPCMD="${STARTCMD}" 

case "$1" in
    start)

	[ $(basename ${LOGDIR}) = "abusehelper" ] || \
            myerr "Logdir needs to end 'abusehelper' subdir."

        echo "Running ${SU} ${USER} -c \"${STARTCMD} >${LOG} 2>&1\""
        ${SU} ${USER} -c "${STARTCMD} >${LOG} 2>&1" &
	;;

    stop)
	echo "ps auxww|fgrep \"${STOPCMD}\"|fgrep -v \"${SU}\""  
	for i in $(ps auxww|fgrep "${STOPCMD}"|fgrep -v "${SU}" | \
	    fgrep -v fgrep |fgrep -v bas | awk  '{print $2}')
	do
	    echo "kill $i"
            ${SU} ${USER} -c "kill $i"
	done
	;;

    restart)
	$0 stop
	sleep 3
	$0 start
	;;
    status)
	echo -e 'Below is a list of currently running AbuseHelper processes:\n'
	ps auxww|fgrep 'abusehelper'|fgrep "${PYTHON}" | \
            fgrep -v "${SU}"|fgrep -v fgrep | \
	    fgrep -v 'sh -c' | tr -s " "  
	;;

    *)
	myerr "Usage: $0 <start|stop|status>"
esac
