#!/bin/sh 
myerr() {
 echo "$*" >&2
 exit 1
}

create_logdir() {
  #doublecheck
  [ $(basename ${LOGDIR}) = "abusehelper" ] || \
      myerr "Logdir needs to end 'abusehelper' subdir."

  mkdir ${LOGDIR} || myerr "Could not create logdir."
  echo "Created ${LOGDIR}..."

  chown ${USER} ${LOGDIR} || myerr "Could not chown to ${USER}"
  echo "chowned to ${USER}..."
  
  chmod 700 ${LOGDIR}
}
INSTALLROOT=""
# The native logging will be improved next. Now we just dump stdout &stderr
# to a single file.

LOGDIR="${INSTALLROOT}/var/log/abusehelper"
LOG="${LOGDIR}/abusehelper.log"

USER="abusehel"

CFG="/etc/abusehelper/config.ini"
AHCMD="python -u -m abusehelper.core.startup"
STARTCMD="${AHCMD} ${CFG}"



case "$1" in
    start)

	[ $(basename ${LOGDIR}) = "abusehelper" ] || \
            myerr "Logdir needs to end 'abusehelper' subdir."

	[ -d ${LOGDIR} ] || create_logdir

        su -c "${STARTCMD} >${LOG} 2>&1" ${USER} &
	;;

    stop)
	pkill -f "${STARTCMD}"
	;;

    restart)
	$0 stop
	sleep 3
	$0 start
	;;
    status)
	pgrep -l -f "python -u -m abusehelper"
	;;
    init)
	echo 'nothing yet'
	;;
    *)
	myerr "Usage: $0 <start|stop|status>"
esac
