#!/bin/sh 
myerr() {
 echo "$*" >&2
 exit 1
}

create_logdir() {
  #doublecheck
  [ $(basename ${LOGDIR}) = "abusehelper" ] || \
      myerr "Logdir needs to end 'abusehelper' subdir."

  mkdir ${LOGDIR} || myerr "Could not create logdir."
  echo "Created ${LOGDIR}..."

  chown ${USER} ${LOGDIR} || myerr "Could not chown to ${USER}"
  echo "chowned to ${USER}..."
  
  chmod 700 ${LOGDIR}
}
INSTALLROOT=""
# The native logging will be improved next. Now we just dump stdout &stderr
# to a single file.

LOGDIR="${INSTALLROOT}/var/log/abusehelper"
LOG="${LOGDIR}/abusehelper.log"

USER="abusehel"

CFG="/etc/abusehelper/config.ini"
AHCMD="python -u -m abusehelper.core.startup"
STARTCMD="${AHCMD} ${CFG}"

case $(uname) in
    Darwin)
	SU="su -"
	;;
    *)
	SU="su"
	;;
esac

case "$1" in
    start)

	[ $(basename ${LOGDIR}) = "abusehelper" ] || \
            myerr "Logdir needs to end 'abusehelper' subdir."

	[ -d ${LOGDIR} ] || create_logdir

        ${SU} ${USER} -c "${STARTCMD} >${LOG} 2>&1" &
	;;

    stop)
	for i in $(ps aux|fgrep "${STARTCMD}"|fgrep -v ${SU} | \
	    fgrep -v fgrep |fgrep -v bas | awk  '{print $2}')
	do
	    echo "kill $i"
            ${SU} ${USER} -c "kill $i"
	done

	#pkill -f "${STARTCMD}"
	;;

    restart)
	$0 stop
	sleep 3
	$0 start
	;;
    status)
	ps aux|fgrep 'abusehelper'|fgrep 'python' |fgrep -v ${SU}|fgrep -v fgrep | \
	        fgrep -v 'sh -c'| tr -s " "  

	;;
    init)
	echo 'nothing yet'
	;;
    *)
	myerr "Usage: $0 <start|stop|status>"
esac
